theme: epv-hugo-theme
_merge: deep
outputFormats:
  pagedjs:
    baseName: pagedjs
    isHTML: true
    mediaType: text/html
    permalinkable: true
    rel: pagedjs
outputs:
  page:
  - html
  section:
  - html
  - rss
pagination:
  pagerSize: 72
params:
  debug:
    productionUrl: https://www.reseauexcellence.fr
  plausible: reseauexcellence.fr